version: "2"
services:
  db:
    image: couchbase
    volumes:
      - ~/couchbase:/opt/couchbase/var
    ports: 
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  web:
    image: arungupta/wildfly
    environment: 
    - COUCHBASE_URI=db
    ports: 
    - 8080:8080
    - 9990:9990
    
